using StorageInventory.Core;
using StorageInventory.Core.Identity;
using StorageInventory.History.Identity;
using StorageInventory.History.Library;

namespace StorageInventory.Library;

// The abstract row stream of the one-transaction import primitive (C4). It is NOT C5's spool importer: it exists so that the
// database, schema and durability engine can be exercised and measured, and it carries exactly the data §9.2 stores. C5 connects
// it to a sealed, verified spool. Names are exact UTF-16LE code units in byte arrays (NAME-01); times are UTC .NET ticks.

/// <summary>An attempt created by T0 and still InProgress; T-IMPORT proves it belongs to this session and capture (IMP-05 d).</summary>
internal sealed record AttemptRef(long AttemptId, byte[] CaptureToken);

/// <summary>The volume row to create (IMP-03 step 1).</summary>
internal sealed record ImportVolumeSpec(string FsType, long? Serial64, long? Serial32, IdentityConfidence Confidence, string DisplayName, byte[]? LastLabel, long? CapacityBytes);

/// <summary>Which source the snapshot belongs to: an existing one (re-read inside the transaction; <c>SourceChanged</c> if it
/// is gone) or a new one created inside the transaction.</summary>
internal abstract record ImportSourceSpec
{
    private ImportSourceSpec() { }

    internal sealed record Existing(long SourceId) : ImportSourceSpec;

    /// <summary>A new source. For a local source give <paramref name="ExistingVolumeId"/> or a <paramref name="NewVolume"/>; for a
    /// network source give the network root and its comparison key.</summary>
    internal sealed record NewSource(SourceKind Kind, long? ExistingVolumeId, ImportVolumeSpec? NewVolume, byte[]? NetworkRoot, byte[]? NetworkRootKey,
        byte[] RootInVolume, IdentityConfidence Confidence, IdentityBasis Basis, string DisplayName) : ImportSourceSpec;
}

/// <summary>Every <c>snapshot</c> column that is not generated by the importer: provenance, observed location, sealed totals.</summary>
internal sealed record ImportSnapshotHeader
{
    public required ScanCompletionState Completion { get; init; }
    public required string RunId { get; init; }
    public required long StartedUtcTicks { get; init; }
    public required long FinishedUtcTicks { get; init; }
    public required byte[] RootPathAsEntered { get; init; }
    public required byte[] CanonicalRoot { get; init; }
    public byte[]? MountPoint { get; init; }
    public byte[]? VolumeLabel { get; init; }
    public long? CapacityBytes { get; init; }
    public long? FreeBytes { get; init; }
    public byte[]? RootDirFileId { get; init; }
    public required IdentityConfidence Confidence { get; init; }
    public required IdentityBasis Basis { get; init; }
    public string? IdentityNote { get; init; }
    public required SourceKind CaptureKind { get; init; }
    public string? FsName { get; init; }
    public LibraryInsideSource LibraryInsideSource { get; init; } = LibraryInsideSource.No;
    public byte[]? LibraryRelPath { get; init; }

    // sealed totals (checked against the data inside the transaction, D-47)
    public required long Files { get; init; }
    public required long Folders { get; init; }
    public required long Bytes { get; init; }
    public long ScanErrors { get; init; }
    public long ReparsePointsSkipped { get; init; }
    public long FileReparsePoints { get; init; }
    public long LocallyIncompleteFolders { get; init; }
    public long AffectedAncestorFolders { get; init; }
}

/// <summary>A finalised folder (SPOOL-20 record 0x03). Indexes are the scan's folder indexes: 0 is the root, parents precede children.</summary>
internal sealed record ImportFolder(int Index, int ParentIndex, byte[] Name, FolderScanStatus Status, ScanErrorType? StatusReason, bool SubtreeComplete,
    int Attributes, long? CreatedTicks, long? ModifiedTicks, long DirectBytes, long TotalBytes, long DirectFiles, long TotalFiles,
    long DirectSubfolders, long TotalSubfolders, long? LargestFileBytes);

/// <summary>A file observation. <see cref="Seq"/> is the scan's emission sequence (SCH-12): across the snapshot each value
/// 0 .. files-1 appears exactly once.</summary>
internal sealed record ImportFile(byte[] Name, long Seq, long Size, long? ModifiedTicks, long? CreatedTicks, long? AccessedTicks, int Attributes);

/// <summary>A scan error record; <see cref="RelativePath"/> is root-relative UTF-16 ('.' = root).</summary>
internal sealed record ImportError(long Seq, byte[] RelativePath, ScanErrorType Type, byte[] Message);

/// <summary>
/// The rows of one snapshot, as an abstract stream. The folder section arrives in ascending discovery index with parents first
/// (IMP-03 step 3); the file records of a folder are read by folder index, so the importer can visit folders in key order
/// (<c>path_id</c>), which is how a real spool's run index is used (IMP-03 step 4).
/// </summary>
internal interface ISnapshotRowSource
{
    /// <summary>The number of folders, root included.</summary>
    int FolderCount { get; }

    IEnumerable<ImportFolder> Folders();

    /// <summary>The files directly in one folder, in any order (the importer sorts them by name id). May be empty.</summary>
    IReadOnlyList<ImportFile> FilesOfFolder(int folderIndex);

    IEnumerable<ImportError> Errors();
}

/// <summary>Progress and test seams for the import. Production passes none.</summary>
internal sealed class ImportOptions
{
    /// <summary>Called every 16,384 file rows with the running count, after the lease has been checked (OBS-15).</summary>
    internal Action<long>? OnFileRows { get; init; }

    /// <summary>Called once after all rows are inserted and before verification (a place to pause or crash a child process).</summary>
    internal Action? AfterRows { get; init; }
}

/// <summary>The numbers an import measured about itself.</summary>
/// <param name="SnapshotId">The id the snapshot was published under (SCH-11).</param>
/// <param name="SourceId">The source it belongs to.</param>
/// <param name="Files">File rows inserted.</param>
/// <param name="Folders">Folder rows inserted.</param>
/// <param name="ScanErrors">Scan error rows inserted.</param>
/// <param name="NewNames">Names that were new to the dictionary.</param>
/// <param name="Elapsed">Duration of the whole transaction, BEGIN to COMMIT.</param>
/// <param name="PeakJournalBytes">The largest the rollback journal was seen while the transaction ran (sampled).</param>
/// <param name="Phases">Where the transaction's time went.</param>
internal sealed record ImportResult(long SnapshotId, long SourceId, long Files, long Folders, long ScanErrors, long NewNames, TimeSpan Elapsed, long PeakJournalBytes, ImportPhases? Phases = null);

/// <summary>Where one import transaction spent its time (IMP-03 to IMP-06): interning and inserting folders, interning and inserting
/// files (names included), the error records and extension totals, the in-transaction verification (IMP-05), and the commit.</summary>
internal sealed record ImportPhases(TimeSpan Folders, TimeSpan Files, TimeSpan Errors, TimeSpan Verification, TimeSpan Commit)
{
    /// <summary>The row-insertion phases alone (names, folders, files, errors): the "import throughput" of PERF-01 without the verification.</summary>
    internal TimeSpan Insertion => Folders + Files + Errors;
}

/// <summary>A failed import, classified for T-OUTCOME (SnapshotFailed, §9.4). The transaction has been rolled back.</summary>
internal sealed class ImportException(CaptureFailureKind kind, string message, Exception? inner = null) : Exception(message, inner)
{
    internal CaptureFailureKind Kind { get; } = kind;
}

/// <summary>A failed deletion; the transaction has been rolled back.</summary>
internal sealed class DeleteException(string message, Exception? inner = null) : Exception(message, inner);
